// <auto-generated />
// 파일 용도: InitialCreate migration의 EF Core 모델 메타데이터를 보관한다.
// 파일 목적: migration 도구가 생성 시점의 모델 상태를 비교할 수 있게 한다.
using System;
using MeetSettle.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeetSettle.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611015108_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeetSettle.Api.Models.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("MeetupId")
                        .HasColumnType("uuid")
                        .HasColumnName("meetup_id");

                    b.Property<Guid>("PayerParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("payer_participant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("MeetupId")
                        .HasDatabaseName("ix_expenses_meetup_id");

                    b.HasIndex("PayerParticipantId");

                    b.ToTable("expenses", null, t =>
                        {
                            t.HasCheckConstraint("ck_expenses_amount_non_negative", "amount >= 0");
                        });
                });

            modelBuilder.Entity("MeetSettle.Api.Models.ExpenseShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("expense_id");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.Property<decimal>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasDefaultValue(1m)
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("ExpenseId", "ParticipantId")
                        .IsUnique()
                        .HasDatabaseName("ux_expense_shares_expense_id_participant_id");

                    b.ToTable("expense_shares", null, t =>
                        {
                            t.HasCheckConstraint("ck_expense_shares_weight_positive", "weight > 0");
                        });
                });

            modelBuilder.Entity("MeetSettle.Api.Models.InviteToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("MeetupId")
                        .HasColumnType("uuid")
                        .HasColumnName("meetup_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("MeetupId");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ux_invite_tokens_token");

                    b.ToTable("invite_tokens", (string)null);
                });

            modelBuilder.Entity("MeetSettle.Api.Models.Meetup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Location")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_meetups_date");

                    b.ToTable("meetups", (string)null);
                });

            modelBuilder.Entity("MeetSettle.Api.Models.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsAttending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_attending");

                    b.Property<Guid>("MeetupId")
                        .HasColumnType("uuid")
                        .HasColumnName("meetup_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("MeetupId", "Name")
                        .HasDatabaseName("ix_participants_meetup_id_name");

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("MeetSettle.Api.Models.SettlementTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FromParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_participant_id");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<Guid>("MeetupId")
                        .HasColumnType("uuid")
                        .HasColumnName("meetup_id");

                    b.Property<Guid>("ToParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_participant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("FromParticipantId");

                    b.HasIndex("MeetupId")
                        .HasDatabaseName("ix_settlement_transfers_meetup_id");

                    b.HasIndex("ToParticipantId");

                    b.ToTable("settlement_transfers", null, t =>
                        {
                            t.HasCheckConstraint("ck_settlement_transfers_amount_positive", "amount > 0");
                        });
                });

            modelBuilder.Entity("MeetSettle.Api.Models.Expense", b =>
                {
                    b.HasOne("MeetSettle.Api.Models.Meetup", "Meetup")
                        .WithMany("Expenses")
                        .HasForeignKey("MeetupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeetSettle.Api.Models.Participant", "PayerParticipant")
                        .WithMany()
                        .HasForeignKey("PayerParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meetup");

                    b.Navigation("PayerParticipant");
                });

            modelBuilder.Entity("MeetSettle.Api.Models.ExpenseShare", b =>
                {
                    b.HasOne("MeetSettle.Api.Models.Expense", "Expense")
                        .WithMany("Shares")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeetSettle.Api.Models.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expense");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("MeetSettle.Api.Models.InviteToken", b =>
                {
                    b.HasOne("MeetSettle.Api.Models.Meetup", "Meetup")
                        .WithMany("InviteTokens")
                        .HasForeignKey("MeetupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meetup");
                });

            modelBuilder.Entity("MeetSettle.Api.Models.Participant", b =>
                {
                    b.HasOne("MeetSettle.Api.Models.Meetup", "Meetup")
                        .WithMany("Participants")
                        .HasForeignKey("MeetupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meetup");
                });

            modelBuilder.Entity("MeetSettle.Api.Models.SettlementTransfer", b =>
                {
                    b.HasOne("MeetSettle.Api.Models.Participant", "FromParticipant")
                        .WithMany()
                        .HasForeignKey("FromParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeetSettle.Api.Models.Meetup", "Meetup")
                        .WithMany("SettlementTransfers")
                        .HasForeignKey("MeetupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeetSettle.Api.Models.Participant", "ToParticipant")
                        .WithMany()
                        .HasForeignKey("ToParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromParticipant");

                    b.Navigation("Meetup");

                    b.Navigation("ToParticipant");
                });

            modelBuilder.Entity("MeetSettle.Api.Models.Expense", b =>
                {
                    b.Navigation("Shares");
                });

            modelBuilder.Entity("MeetSettle.Api.Models.Meetup", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("InviteTokens");

                    b.Navigation("Participants");

                    b.Navigation("SettlementTransfers");
                });
#pragma warning restore 612, 618
        }
    }
}
